<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="//fonts.googleapis.com/css?family=Roboto+Slab|Roboto+Mono|Roboto+Condensed|Roboto" rel="stylesheet" type="text/css"></link>
    <link href="/css/template.css" rel="stylesheet" type="text/css"></link>
    <link href="/css/slider.css" rel="stylesheet" type="text/css"></link>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="//code.highcharts.com/highcharts.js"></script>
  </head>
  <body>